doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        charset: utf8
        types:
            uuid: 'Symfony\Bridge\Doctrine\Types\UuidType'
        mapping_types:
            enum: string
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            # User Bounded Context
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'
                alias: User
            
            # Snippet Bounded Context
            Snippet:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Snippet/Domain/Entity'
                prefix: 'App\Snippet\Domain\Entity'
                alias: Snippet
            
            # Attachment Bounded Context
            Attachment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Attachment/Domain/Entity'
                prefix: 'App\Attachment\Domain\Entity'
                alias: Attachment
            
            # Sharing Bounded Context
            Sharing:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Sharing/Domain/Entity'
                prefix: 'App\Sharing\Domain\Entity'
                alias: Sharing
            
            # Integration and Collaboration BCs will be added when implemented
            # Integration:
            #     type: attribute
            #     is_bundle: false
            #     dir: '%kernel.project_dir%/src/Integration/Domain/Entity'
            #     prefix: 'App\Integration\Domain\Entity'
            #     alias: Integration
            # 
            # Collaboration:
            #     type: attribute
            #     is_bundle: false
            #     dir: '%kernel.project_dir%/src/Collaboration/Domain/Entity'
            #     prefix: 'App\Collaboration\Domain\Entity'
            #     alias: Collaboration
            
            # Token Bounded Context
            Token:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Token/Domain/Entity'
                prefix: 'App\Token\Domain\Entity'
                alias: Token
            
            # Billing Bounded Context
            Billing:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Billing/Domain/Entity'
                prefix: 'App\Billing\Domain\Entity'
                alias: Billing
            
            # Analytics Bounded Context
            Analytics:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Analytics/Domain/Entity'
                prefix: 'App\Analytics\Domain\Entity'
                alias: Analytics
            
            # Legacy mapping for Share entity still in old location
            ShareLegacy:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Share/Entity'
                prefix: 'App\Domain\Share\Entity'
                alias: ShareLegacy
        dql:
            string_functions:
                # Enable PostgreSQL-specific functions
                REGEXP: App\DQL\RegexpFunction
            datetime_functions:
                # Add custom date functions if needed
            numeric_functions:
                # Add custom numeric functions if needed
        
        # Enable second level cache for better performance
        second_level_cache:
            enabled: true
            log_enabled: '%kernel.debug%'
            regions:
                users_region:
                    cache_driver:
                        type: pool
                        pool: cache.users
                    lifetime: 3600
                snippets_region:
                    cache_driver:
                        type: pool
                        pool: cache.snippets
                    lifetime: 1800

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.query_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.query_cache_pool:
                    adapter: cache.app