doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        charset: utf8
        types:
            uuid: 'Symfony\Component\Uid\UuidType'
        mapping_types:
            enum: string
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                # Enable PostgreSQL-specific functions
                REGEXP: App\DQL\RegexpFunction
            datetime_functions:
                # Add custom date functions if needed
            numeric_functions:
                # Add custom numeric functions if needed
        
        # Enable second level cache for better performance
        second_level_cache:
            enabled: true
            log_enabled: '%kernel.debug%'
            regions:
                users_region:
                    cache_driver:
                        type: pool
                        pool: cache.users
                    lifetime: 3600
                snippets_region:
                    cache_driver:
                        type: pool
                        pool: cache.snippets
                    lifetime: 1800

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.query_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.query_cache_pool:
                    adapter: cache.app