nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-API-Key']
        expose_headers: ['Link', 'X-Total-Count', 'X-Rate-Limit-Remaining', 'X-Rate-Limit-Limit']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

when@prod:
    nelmio_cors:
        defaults:
            # Restrict CORS in production
            allow_origin: ['https://prettiops.com', 'https://app.prettiops.com']
            allow_credentials: true