# Platform.sh application configuration
name: app
type: php:8.2

runtime:
    extensions:
        - redis
        - pdo_pgsql
        - sodium

variables:
    env:
        APP_ENV: 'prod'
        APP_DEBUG: '0'
        APP_SECRET: '%env(PLATFORM_PROJECT_ENTROPY)%'

build:
    flavor: composer

dependencies:
    nodejs:
        npm: "9"

hooks:
    build: |
        set -e
        # Install Node.js dependencies
        npm install
        npm run build
        
    deploy: |
        set -e
        php bin/console cache:clear --env=prod --no-debug
        php bin/console cache:warmup --env=prod --no-debug
        php bin/console assets:install --env=prod --no-debug
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            allow: false
            rules:
                \.(css|js|gif|jpe?g|png|svg|ico|woff2?|ttf|eot)$:
                    allow: true
                    expires: 1w
                ^/robots\.txt$:
                    allow: true
                ^/sitemap\.xml$:
                    allow: true

disk: 2048

relationships:
    database: "database:postgresql"
    redis: "redis:redis"

mounts:
    'var': { source: local, source_path: var }
    'public/uploads': { source: local, source_path: uploads }