api_platform:
    defaults:
        cache_headers:
            max_age: 3600
            shared_max_age: 86400
            public: true
            vary: ['Content-Type', 'Authorization']
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']