framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            cache.snippets:
                adapter: cache.adapter.redis
            cache.users:
                adapter: cache.adapter.redis
            cache.rate_limits:
                adapter: cache.adapter.redis
    session:
        handler_id: '%env(REDIS_URL)%'