# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_directory: '%env(default:kernel.project_dir:UPLOAD_BASE_PATH)%/public/uploads'
    encryption_key: '%env(default:default_encryption_key:ENCRYPTION_KEY)%'
    max_file_size: '%env(default:default_max_file_size:MAX_FILE_SIZE)%'
    default_encryption_key: 'temporary_key_replace_in_production'
    default_max_file_size: '10485760'
    default_cipher: 'aes-256-cbc'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically inject dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/ValueObject/'
            - '../src/Domain/*/Event/'

    # Domain Services
    App\Domain\:
        resource: '../src/Domain/*/Service/'
        
    # Application Layer Services
    App\Application\:
        resource: '../src/Application/'
        
    # Infrastructure Services
    App\Infrastructure\:
        resource: '../src/Infrastructure/'
        
    # UI Controllers  
    App\UI\:
        resource: '../src/UI/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Encryption Service (now in Infrastructure)
    App\Infrastructure\Security\EncryptionService:
        arguments:
            $encryptionKey: '%encryption_key%'
            $cipher: '%env(default:default_cipher:AES_CIPHER)%'

    # Token Masking Service (now in Infrastructure)
    App\Infrastructure\Security\TokenMaskingService: ~

    # Security Services (now in Infrastructure)
    App\Infrastructure\Security\SecurityService: ~
    App\Infrastructure\Security\OAuth2\JwtTokenService: ~

    # Rate Limiting
    App\EventListener\RateLimitListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # RGPD Services (now in Infrastructure)
    App\Infrastructure\Security\RgpdComplianceService: ~

    # File Upload Services (now in Infrastructure)
    App\Infrastructure\Storage\FileUploadService:
        arguments:
            $uploadDirectory: '%upload_directory%'
            $maxFileSize: '%max_file_size%'

    # Repository Interface Bindings
    App\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\UserRepository
        
    App\Domain\Snippet\Repository\SnippetRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\SnippetRepository
        
    App\Domain\Share\Repository\ShareRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\ShareRepository
        
    App\Domain\Snippet\Repository\AttachmentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\AttachmentRepository
        
    App\Domain\Snippet\Repository\FavoriteRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\FavoriteRepository

    # Legacy Repository Services (for backward compatibility)
    App\Repository\UserRepository:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\UserRepository
    App\Repository\SnippetRepository:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\SnippetRepository
    App\Repository\ShareRepository:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\ShareRepository
    App\Repository\AttachmentRepository:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\AttachmentRepository
    App\Repository\FavoriteRepository:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\FavoriteRepository
    
    # Service aliases for backward compatibility
    App\Service\EncryptionService:
        alias: App\Infrastructure\Security\EncryptionService
    App\Service\TokenMaskingService:
        alias: App\Infrastructure\Security\TokenMaskingService
    App\Service\SecurityService:
        alias: App\Infrastructure\Security\SecurityService
    App\Service\RgpdComplianceService:
        alias: App\Infrastructure\Security\RgpdComplianceService
    App\Service\FileUploadService:
        alias: App\Infrastructure\Storage\FileUploadService
    App\Security\JwtTokenService:
        alias: App\Infrastructure\Security\OAuth2\JwtTokenService
    App\Security\AppCustomAuthenticator:
        alias: App\Infrastructure\Security\OAuth2\AppCustomAuthenticator