# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_directory: '%env(default:kernel.project_dir:UPLOAD_BASE_PATH)%/public/uploads'
    encryption_key: '%env(default:default_encryption_key:ENCRYPTION_KEY)%'
    max_file_size: '%env(default:default_max_file_size:MAX_FILE_SIZE)%'
    default_encryption_key: 'temporary_key_replace_in_production'
    default_max_file_size: '10485760'
    default_cipher: 'aes-256-cbc'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically inject dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/*/Domain/Entity/'
            - '../src/*/Domain/ValueObject/'
            - '../src/*/Domain/Event/'
            - '../src/Domain/'
            - '../src/Infrastructure/'
            - '../src/Application/'
            - '../src/UI/'

    # Bounded Context Services (DDD Structure)
    App\Shared\:
        resource: '../src/Shared/'
        
    App\User\:
        resource: '../src/User/'
        
    App\Snippet\:
        resource: '../src/Snippet/'
        
    App\Sharing\:
        resource: '../src/Sharing/'
        
    App\Attachment\:
        resource: '../src/Attachment/'
        
    App\Token\:
        resource: '../src/Token/'
        
    App\Billing\:
        resource: '../src/Billing/'
        
    App\Analytics\:
        resource: '../src/Analytics/'
        
    # Integration and Collaboration BCs will be added when implemented
    # App\Integration\:
    #     resource: '../src/Integration/'
    #     
    # App\Collaboration\:
    #     resource: '../src/Collaboration/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Encryption Service (now in Shared Infrastructure)
    App\Shared\Infrastructure\Security\Encryption\EncryptionService:
        arguments:
            $encryptionKey: '%encryption_key%'
            $cipher: '%env(default:default_cipher:AES_CIPHER)%'

    # Token Masking Service (now in Shared Infrastructure)
    App\Shared\Infrastructure\Security\TokenMaskingService: ~

    # Security Services (now in User Infrastructure)
    App\User\Infrastructure\Security\SecurityService: ~
    App\User\Infrastructure\Security\OAuth2\JwtTokenService: ~

    # Rate Limiting
    App\EventListener\RateLimitListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # RGPD Services (now in User Infrastructure)
    App\User\Infrastructure\Security\RgpdComplianceService: ~

    # File Upload Services (now in Attachment Infrastructure)
    App\Attachment\Infrastructure\Storage\FileUploadService:
        arguments:
            $uploadDirectory: '%upload_directory%'
            $maxFileSize: '%max_file_size%'

    # Repository Interface Bindings (DDD Structure)
    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Persistence\Doctrine\UserRepository
        
    App\Snippet\Domain\Repository\SnippetRepositoryInterface:
        alias: App\Snippet\Infrastructure\Persistence\Doctrine\SnippetRepository
        
    App\Sharing\Domain\Repository\ShareRepositoryInterface:
        alias: App\Sharing\Infrastructure\Persistence\Doctrine\ShareRepository
        
    App\Attachment\Domain\Repository\AttachmentRepositoryInterface:
        alias: App\Attachment\Infrastructure\Persistence\Doctrine\AttachmentRepository
        
    App\Snippet\Domain\Repository\FavoriteRepositoryInterface:
        alias: App\Snippet\Infrastructure\Persistence\Doctrine\FavoriteRepository

    # Legacy Repository Services (for backward compatibility)
    App\Repository\UserRepository:
        alias: App\User\Infrastructure\Persistence\Doctrine\UserRepository
    App\Repository\SnippetRepository:
        alias: App\Snippet\Infrastructure\Persistence\Doctrine\SnippetRepository
    App\Repository\ShareRepository:
        alias: App\Sharing\Infrastructure\Persistence\Doctrine\ShareRepository
    App\Repository\AttachmentRepository:
        alias: App\Attachment\Infrastructure\Persistence\Doctrine\AttachmentRepository
    App\Repository\FavoriteRepository:
        alias: App\Snippet\Infrastructure\Persistence\Doctrine\FavoriteRepository
    
    # Service aliases for backward compatibility
    App\Service\EncryptionService:
        alias: App\Shared\Infrastructure\Security\Encryption\EncryptionService
    App\Service\TokenMaskingService:
        alias: App\Shared\Infrastructure\Security\TokenMaskingService
    App\Service\SecurityService:
        alias: App\User\Infrastructure\Security\SecurityService
    App\Service\RgpdComplianceService:
        alias: App\User\Infrastructure\Security\RgpdComplianceService
    App\Service\FileUploadService:
        alias: App\Attachment\Infrastructure\Storage\FileUploadService
    App\Security\JwtTokenService:
        alias: App\User\Infrastructure\Security\OAuth2\JwtTokenService
    App\Security\AppCustomAuthenticator:
        alias: App\User\Infrastructure\Security\OAuth2\AppCustomAuthenticator