# Platform.sh services configuration

database:
    type: postgresql:16
    disk: 2048
    configuration:
        max_connections: 200
        shared_preload_libraries: pg_stat_statements
        log_min_duration_statement: 100
        
redis:
    type: redis:7.0
    disk: 256